name: Build and Push Docker Image

on:
  push:
    tags: # Trigger this workflow only when a Git tag is pushed
      - '*'

jobs:
  build-and-push:
    - name: Build and Push with Cache
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: xowlpost/glibc:${{ env.tag }}
        cache-from: type=registry,ref=xowlpost/glibc:cache
        cache-to: type=registry,ref=xowlpost/glibc:cache,mode=max

    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Extract Git Tag
      id: extract_tag
      run: echo "tag=$(git describe --tags)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Multi-Architecture Docker Image
      run: |
        chmod +x ./build-and-push.sh
        ./build-and-push.sh xowlpost/glibc ${{ env.tag }} "linux/amd64,linux/arm64"
