name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Multi-Architecture Docker Image
      run: |
        chmod +x ./build-and-push.sh
        ./build-and-push.sh xowlpost/glibc 2.38 "linux/amd64,linux/arm64"

    - name: Verify Image
      run: |
        docker buildx imagetools inspect xowlpost/glibc:2.38
